name: Lint

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'none'

      - name: Setup Yarn (Corepack)
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate
          corepack yarn --version

      - name: Install dependencies
        run: corepack yarn install --immutable

      - name: Run linter
        run: corepack yarn lint
