name: Lint

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack (Yarn 4)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run linter
        run: yarn lint
